




.build/uno/src/arduino_control.cpp : src/arduino_control.ino
	@mkdir -p .build/uno/src
	@echo [93msrc/arduino_control.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/uno/src/arduino_control.cpp
	@true

